### ISSUE TITLE
Omnifunc support

### ISSUE THREAD

**Issue by jose-elias-alvarez** [folke/lua-dev.nvim#10]
Thanks for the great plugin! It works amazingly well out-of-the-box.

I see that the plugin depends on a "full" completion plugin to work properly, since the built-in `vim.lsp.omnifunc` seems to simply return a gigantic list of all available completion options, regardless of the current context. I'm curious whether this is a fundamental limitation or whether there's any chance of getting omnifunc support. If it's the latter, I'd be happy to contribute towards getting it to work.

**Comment by jose-elias-alvarez** [comment]
Update: I realized this is actually related to a recent update to `lua-language-server` itself. Sorry for the trouble!

**Comment by folke** [comment]
Hi José, sorry, didn't have the time yet to look into this, but glad it's not related to this plugin.

But you're saying that sumneko returns all suggestions for every completion? Maybe post an issue there? Doesn't sound right for sure

**Comment by jose-elias-alvarez** [comment]
No worries, and thanks for putting this together. It's a strange issue, and I think it might be related to `vim.lsp.omnifunc` itself, but I'll investigate. Thanks again!

**Comment by jandamm** [comment]
@jose-elias-alvarez have you been able to resolve this issue?
I'm trying to set up my lua dev environment with `sumneko` and this plugin.
Using omnifunc I don't get any useful values when completing after `vim.api.`

**Comment by jose-elias-alvarez** [comment]
@jandamm Take a look at the Sumneko settings in [defaults.nvim](https://github.com/mjlbach/defaults.nvim/blob/master/init.lua), which work well when using `omnifunc` for runtime files and plugins.

**Comment by jandamm** [comment]
Thank you for the hint. I found a similar snippet in [the lspinstall wiki](https://github.com/kabouzeid/nvim-lspinstall/wiki).
I still wonder why it does not work with lua-dev since it uses  basically the same config. 🤷‍♂️
