### ISSUE TITLE
Can this configuration be loaded only when opening neovim-related files?

### ISSUE THREAD

**Issue by nogweii** [folke/lua-dev.nvim#12]
As the title says:

* If I edit `~/.config/nvim/init.lua` (or any other Lua file in the config directory), then I'd like the LSP started with the additional configuration parameters that makes it awesome
* If I edit `~/.config/awesome/rc.lua` or any other Lua file outside of neovim, then these settings don't apply and I'd like to use a different set.

I'm not sure how to achieve this, do you have an idea?

**Comment by folke** [comment]
You could call `lua-dev` and only set it inside the `on_new_config` method. Please refer to the lsp docs on how to accomplish this.

**Comment by erwin** [comment]
@nogweii we're you able to figure out how to do this?

For me it would also be ideal if I could use `lua-dev` whenever the `.lua` file is under `~/.config/nvim` but not otherwise.

I see that in the `lspconfig` documentation for `on_new_config`:

> `function(new_config, new_root_dir)`
>
> Function executed after a root directory is detected. This is used to modify the server configuration (including `cmd` itself). Most commonly, this is used to inject additional arguments into `cmd`.

Anyone familiar enough with `lspconfig` to provide an example of what this directory test would look like? I'm assuming we're testing that `new_root_dir` isn't `~/.config/nvim`?

Sorry for one of the dumber questions I've ever asked.

I still don't quite really understand how LSP actually works... I probably need to create my own lsp config from scratch...

<details>
<summary>lspconfig.lua</summary>

```
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }

      if server.name == "sumneko_lua" then
        opts.settings = require("lua-dev").setup().settings
      end

      server:setup(opts)
      vim.cmd [[ do User LspAttachBuffers ]]
   end)
end

return M
```
</details>

**Comment by nogweii** [comment]
@erwin yeah, I was able to solve this! Check out my [dotfiles](https://code.aether.earth/nogweii/dotfiles/), in particular my [LSP configuration](https://code.aether.earth/nogweii/dotfiles/-/blob/main/config/nvim/lua/me/lsp/settings.lua) and the [`sumneko_lua` configuration](https://code.aether.earth/nogweii/dotfiles/-/blob/main/config/nvim/lua/me/lsp/configs/sumneko_lua.lua).

Relevant portions of the configs:

<details>
<summary>lsp/settings.lua</summary>

```lua
  local opts = {
    -- map buffer local keybindings when the language server attaches
    on_attach = M.on_attach,
  }

  -- do I have any custom configuration for this LSP server?
  local has_lsp_config, custom_lsp_config = pcall(require, "me.lsp.configs." .. server.name)
  if has_lsp_config then
    opts = vim.tbl_deep_extend("force", opts, custom_lsp_config)
  end
```

</details>

<details>
<summary>lsp/configs/sumneko_lua.lua</summary>


```lua
local neovim_parent_dir = vim.fn.resolve(vim.fn.stdpath("config"))
local buffer_file_name = vim.fn.expand("%:p")

-- is this file in the config directory?
if string.sub(buffer_file_name, 1, string.len(neovim_parent_dir)) == neovim_parent_dir then
  -- yup, so load the awesome settings from folke to teach the LSP about
  -- neovim's APIs
  return require("lua-dev").setup({})
else
  -- not a neovim config file, so no special settings
  return {}
end
```

</details>
