### ISSUE TITLE
"Undefined filed" warnings even though the server scans the files

### ISSUE THREAD

**Issue by p00f** [folke/lua-dev.nvim#13]
PS: Not sure if this is a luadev issue or a sumneko issue

This is from a plugin I wrote using plenary

https://user-images.githubusercontent.com/36493671/120752511-78710000-c527-11eb-9348-4be887ec058d.mp4

Even though hover shows the correct doc/signature for these methods, I get "Undefined field" warnings

**Comment by p00f** [comment]
When I hover on `path` in `p.path.sep` it shows the correct table i.e.
https://github.com/nvim-lua/plenary.nvim/blob/3834d42236c155bb4240fb4008ea6e62c4a21dae/lua/plenary/path.lua#L17-L43

**Comment by folke** [comment]
That seems to be a sumneko issue I think.

The diagnostics are from Sumneko right? You don't have any other lua linter running?

If you do `gd` on `p.path` you get to the correct definition in `plenary.path`?

**Comment by p00f** [comment]
> The diagnostics are from Sumneko right? You don't have any other lua linter running?

Yeah only sumneko

> If you do gd on p.path you get to the correct definition in plenary.path?

Yes

**Comment by folke** [comment]
won't be able to help you there. It seems sumneko is doing something wrong. Best to submit an issue there.
