### ISSUE TITLE
The language server seems extremely slow

### ISSUE THREAD

**Issue by tomaskallup** [folke/lua-dev.nvim#14]
My configuration can be seen [here](https://github.com/tomaskallup/dotfiles/blob/master/nvim/lua/plugins/nvim-lspconfig.lua#L61)

For some reason, when editing a lua file inside a plugin, the server can't quite keep up. I have several minutes delay on diagnostics and completion is unusable (running nvim-compe).

Is there something I can do to debug this or fix this? Before I was running plain sumneko and it was fine (but without all the nice info for nvim functions)

**Comment by folke** [comment]
There are currently issues with sumneko versions higher than 1.20.1. I'm using that version as a workaround. There's an issue upstream about this.

I have an idea that could maybe improve performance with the last version, but still need to check.

**Comment by tomaskallup** [comment]
All right, I'll try to revert my version until it's fixed. Thanks!

**Comment by folke** [comment]
I pushed a [fix](https://github.com/sumneko/lua-language-server/pull/564#event-4902783280) upstream that fixes the performance issues. Once @sumneko makes a new release, I'll close this issue.

**Comment by folke** [comment]
Closing this, since lua-language-server 1.21.3 has been released

**Comment by tomaskallup** [comment]
Just chiming in, with the fresh lua-language-server it's blazing fast! (built from master)
