### ISSUE TITLE
How would I integrate this with kabouzeid/nvim-lspinstall

### ISSUE THREAD

**Issue by DanKGooGLy** [folke/lua-dev.nvim#15]
I've been spending quite a few hours scratching my head as to how I would integrate this with [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall).  
I don't want to have lua-language-server in my `$PATH` but there is no good documentation on nvim-lspinstall that allows me to use this properly. Any idea as to how I would do this?

**Comment by folke** [comment]
Just follow the installation as normal for both `lua-dev` and `lspinstall` and change `sumneko_lua` to `lua` as specified in the [config section](https://github.com/folke/lua-dev.nvim#-setup)

**Comment by DanKGooGLy** [comment]
I'm not quite sure I understand. So I set up `lspinstall`, and then add ```lua
local luadev = require("lua-dev").setup({
})

local lspconfig = require('lspconfig')
lspconfig.lua.setup(luadev)```

**Comment by folke** [comment]
Havent tested this, but something like this:

```lua
lspconfig.lua.setup({
on_new_config = function(config, root_dir)
if root_dir == "the one we want" then
config.settings = require("lua-dev").setup().settings
end
end
})
```

**Comment by folke** [comment]
Sorry, my answer was to another question from another user :)

But yes, your example should work. You did also run `:LspInstall lua` right?

**Comment by DanKGooGLy** [comment]
Yes I did. I ended up getting the error: `attempt to index field 'lua' (a nil value)` on the line of `require('lspconfig).lua.setup`.

**Comment by folke** [comment]
That means you didn't setup lspinstall. See here: https://github.com/kabouzeid/nvim-lspinstall#installation 

That first line require

**Comment by DanKGooGLy** [comment]
Alright, thanks for the help. I managed to come up with 
```lua
require'lspinstall'.setup() -- important

local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup{}
end

require('lspconfig').lua.setup({
  on_new_config = function(config, root_dir)
      if root_dir == vim.fn.stdpath('config') then
        config.settings = require("lua-dev").setup().settings
      end
  end
})
```

**Comment by kabouzeid** [comment]
@DanKGooGLy the following would be a bit cleaner, otherwise your calling lspconfig setup twice for lua, which could cause problems now or in future.

```lua
require'lspinstall'.setup() -- important

local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  local config = {}

  if server == "lua" then
    config.on_new_config = function(config, root_dir)
        if root_dir == vim.fn.stdpath('config') then
          config.settings = require("lua-dev").setup().settings
        end
    end
  end

  require'lspconfig'[server].setup(config)
end
```

**Comment by DanKGooGLy** [comment]
Oh, thank you very much!
