### ISSUE TITLE
Help: Setting up with different completion/lsp clients

### ISSUE THREAD

**Issue by spamwax** [folke/lua-dev.nvim#18]
I am trying to make this work with coc.nvim with no luck so far.
I have setup coc.nvim to use sumneko's LSP.
Do I have to use mentioned completions plugins (nvim-compe or completion-nvim) and `nvim-lspconfig` to make this work? or it's possible to feed this plugins completions to coc.nvim?

**Comment by folke** [comment]
It's meant to be used with the builtin lsp client, but you can try

```lua
require("lua-dev").setup({}).settings
```

You should be able to pass those settings to coc sumneko lsp

**Comment by spamwax** [comment]
Thanks, I did the following and it worked.

```viml
let lua_lsp = glob('~/.vscode/extensions/sumneko.lua*', 0, 1)
let sumneko_setting = luaeval('require("lua-dev").setup({}).settings')
if len(lua_lsp)
    let lua_lsp = lua_lsp[-1] . '/server'
    call coc#config('languageserver', {
    \    'lua-language-server': {
    \        'cwd': lua_lsp,
    \        'command': lua_lsp . '/bin/macOS/lua-language-server',
    \        'args': ['-E', '-e', 'LANG="en-us"', lua_lsp . '/main.lua'],
    \        'settings': sumneko_setting,
    \        'filetypes': ['lua']
    \    }
    \ })
endif
```
Does this only support plugins installed by `packer`?
Also where do I add my current settings to coc since now I am overwriting the settings using the above `luaeval`?
For example, I want to add luarocks or my own modules to sumneko.

**Comment by folke** [comment]
you can  use `vim.tbl_deep_extend("force", your_settings, sumneko_settings)` as your settings. This will merge the lua-dev settings into your existing settings object.
