### ISSUE TITLE
Feature request: add only the provided plugin path to `library`

### ISSUE THREAD

**Issue by dhruvmanila** [folke/lua-dev.nvim#2]
In case of working on only a few plugins, it seems unnecessary to load all of the user's plugins which could be dozens of them and that could mean that the server will have to index a lot of files.

### Proposal

We could extend `library.plugins` key to accept a table of `opt` or `start` plugin names which should be added. So, the type for `library.plugins` would become `boolean|table<string, string[]>`:
- `true`: add all the opt and start plugins
- `false`: do not add any of the plugins
- `table`: containing two keywords `opt` and `start` each with a list of plugin names to be added

**Comment by folke** [comment]
Great idea. Was planning to add something like that. We don't need to check for opt / start. Plugin name is enough.

**Comment by folke** [comment]
I just added this. Thank you for the suggestion!

**Comment by dhruvmanila** [comment]
Awesome, thanks for doing this!
