### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by Trid-collab** [folke/lua-dev.nvim#22]
I am new to this plugin. 
In past I have had lua sumneko server install using lspinstall and configured using the standard config found at the lspinstall site.

	local lua_settings = `{`
 	Lua = {
 		runtime = {
 			-- LuaJIT in the case of Neovim
 			version = "LuaJIT",
 			path = vim.split(package.path, ";"),
 		},
 		diagnostics = {
 			-- Get the language server to recognize the `vim` global
 			globals = { "vim" },
 		},
 		workspace = {
 			-- Make the server aware of Neovim runtime files
 			library = {
 				[vim.fn.expand("$VIMRUNTIME/lua")] = true,
 				[vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
		},

It was kind of working and then I came upon on this plugin of yours and wanted to give it a try. I commented out the above settings and installed your setup with the default settings . I didn't deinstall the  lua completion server installed through lspinstall 

Now its though its running using the configs from this plugin I am getting the following message in Lspinfo. Is there something I am missing in my setup. Also does this plugin give any additional benefit over the setup I had initially

![image](https://user-images.githubusercontent.com/61322708/129445884-22808959-de90-4478-a086-d873630e9677.png)

**Comment by folke** [comment]
You need to specify the full path to the sumneko cmd as a key in `lspconfig` in setup.

This plugin includes stubs with all the definitions of the internal Neovim API, so that you can get proper completion with documentation.
