### ISSUE TITLE
Add explicit warning that this changes the default of `Lua.runtime.path`

### ISSUE THREAD

**Issue by B4rc1** [folke/lua-dev.nvim#23]
This plugin changes the default of `Lua.runtime.path` from `{ "?.lua", "?/init.lua", "?/?.lua" }` to `{ "lua/?.lua", "lua/?/init.lua`.

This caused me almost a day of frustration, as I could not get my lua completion to work correctly: https://github.com/sumneko/lua-language-server/issues/657

Looking back the readme mentions it, but understates what is being done:
> properly configures the require path with lua/?.lua and lua/?/init.
 
I would like it to be more explicit so no one else has to struggle a day for no reason. Something like:
ATTENTION: This Plugin _changes_ the default runtime path, if you would like to use the sumneko lua-language-server for other lua projects add the following to your config:
```lua
local luadev = require("lua-dev").setup({
    lspconfig = {
		-- cmd = {"lua-language-server"},
		settings = {
			Lua = {
				runtime = {
					path = {
						"?.lua",
						"?/?.lua",
                                                "?/init.lua",
					}
				},
			},
		},
	})
```

**Comment by folke** [comment]
The description of the project explicitly mentions that this is a setup for writing your `init.lua` or plugin development.

However, I added an additional warning that this is not intended to be used for any other type of project at https://github.com/folke/lua-dev.nvim#-setup

**Comment by akinsho** [comment]
@folke the PR that fixed this issue unfortunately makes the lsp *much, much* slower. Is there anyway to restrict this change to only people who want what it does?

**Comment by folke** [comment]
@akinsho it's much slower for sure. Will make it configurable https://github.com/folke/lua-dev.nvim/issues/29
