### ISSUE TITLE
No path completion for installed plugins in require function

### ISSUE THREAD

**Issue by MurdeRMelodY** [folke/lua-dev.nvim#24]
I'm not sure why but I only get completion entries for my lua config modules. Is this the intended behaviour?

![2021-08-21-150438_447x193_scrot](https://user-images.githubusercontent.com/63958167/130322813-3dc48dfe-cdfc-465d-bde4-805e651e7920.png)

**Comment by MurdeRMelodY** [comment]
It would seem the issue is that "/lua" gets appended to the library paths.

https://github.com/folke/lua-dev.nvim/blob/e9588503e68fa32ac08b83d9cb7e42ec31b8907d/lua/lua-dev/sumneko.lua#L13-L20

**Comment by folke** [comment]
I just pushed a fix for this in https://github.com/folke/lua-dev.nvim/commit/274f72b6bc5c199f6d2d33956f9aa0603d4c3367

Be aware that completion of require paths of all plugins is pretty slow.

**Comment by yujinyuz** [comment]
@folke I was just wondering. I just want to confirm something, since you said that completion for require paths is slow, does this explain why `nvim-cmp`'s completion takes some time to display available plugins?

**Comment by yujinyuz** [comment]
@folke I was just wondering. I just want to confirm something, since you said that completion for require paths is slow, does this explain why `nvim-cmp`'s completion takes some time to display available plugins?
