### ISSUE TITLE
cmd not defined for "sumneko_lua"

### ISSUE THREAD

**Issue by joelpalmer** [folke/lua-dev.nvim#25]
**_Update_**: Apparently, I may be the only person in _Neovimland_ who _was_ perfectly happy with the completions from this plugin alone. But, if you do have the `lua-language-server` set up then the below will not impact you. 

For those who find this later, this is my proper working configuration for using this plugin _**with**_ `lua-language-server`:
```lua
local lspconfig = require "lspconfig"
local luadev = require("lua-dev").setup {
  lspconfig = {
    cmd = {
      "/Users/joel/vim-dev/sources/lua-language-server/bin/macOS/lua-language-server",
      "-E",
      "/Users/joel/vim-dev/sources/lua-language-server/main.lua",
    },
  },
}
lspconfig.sumneko_lua.setup(luadev)

```
-----
**_Original "issue" when I was happily using this plugin without `lua-language-server`:_**

I'm not sure if this is an issue _per se_. But, when https://github.com/neovim/nvim-lspconfig/pull/1171 landed on 2021-08-24, I began to get the message: `cmd not defined for "sumneko_lua". You must manually set cmd in the setup{} call according to CONFIG.md` when opening any Lua file. This makes perfect sense since [the PR](https://github.com/neovim/nvim-lspconfig/pull/1171) "unsilenced" the message. I'm using the default `lua-dev` setup as shown here: https://github.com/folke/lua-dev.nvim#-setup. Everything still worked perfectly fine. But, the message is distracting. 

So, Instead of adding an extra conditional branch to `nvim-lspconfig` (locally) that ignored `sumneko_lua`, I decided to just set `enabled` to `false` as shown below in order to fall into _this_ conditional branch: https://github.com/neovim/nvim-lspconfig/blob/62b9e1a27dd0c9556964b5c7a7bc144091cf9709/lua/lspconfig/util.lua#L230. This gets rid of the message _and_ everything still works just fine. 

This may not be the best solution. So, please let me know if I should be doing something different. Otherwise, I hope it helps others that may run into this. 

```lua
local luadev = require("lua-dev").setup {
  -- was either this or keep local nvim-lspconfig & suppress error
  -- for sumneko_lua here:
  -- https://github.com/neovim/nvim-lspconfig/blob/62b9e1a27dd0c9556964b5c7a7bc144091cf9709/lua/lspconfig/util.lua#L233
  -- @TODOUA: watch for related changes in lua-dev and nvim-lspconfig
  lspconfig = {
    enabled = false,
  },
}

local lspconfig = require "lspconfig"
lspconfig.sumneko_lua.setup(luadev)

```

**Comment by Trid-collab** [comment]
Thank you for your update. It helped. I am new to this. Need a clarity.
I have installed lua server through the lspInstall plugin and keep updating it to the latest version.
And then I have installed the Lua dev plugin and now have configured it the way you mentioned. 
I am seeing two lua servers attached when I do LspInfo. Question is do I need to install the lua server using the "kabouzeid/nvim-lspinstall" at all if I am using this "folke/lua-dev" 
If I don't , then can I deinstall the lua server installed through the lspinstall plugin
Then how does the lua server installed with the lua-dev plugin get updated

![image](https://user-images.githubusercontent.com/61322708/131518521-9b60456c-478f-4dea-9f8b-5dbc6e7e8dc6.png)
