### ISSUE TITLE
Question: How did you get the builtin-docs.json file？

### ISSUE THREAD

**Issue by backtolife2021** [folke/lua-dev.nvim#27]

**Comment by dmitmel** [comment]
https://github.com/iamcco/vim-language-server/blob/10a9ae92d5b00da86eaf100e1b062ab7201dfdcc/src/docs/builtin-docs.json
https://github.com/iamcco/vim-language-server/blob/10a9ae92d5b00da86eaf100e1b062ab7201dfdcc/src/script/build-docs.ts

**Comment by backtolife2021** [comment]
Thank you for the information @dmitmel
