### ISSUE TITLE
Unwanted default opts for lspconfig setup

### ISSUE THREAD

**Issue by wookayin** [folke/lua-dev.nvim#35]
`require("lua-dev").setup { ... }` produces the following opts for `lspconfig.sumneko_lua`:

```
  Lua = {
        ...
        completion = { callSnippet = "Replace" },
        workspace = {
          -- Make the server aware of Neovim runtime files
          library = M.library(opts),
          maxPreload = 1000,
          preloadFileSize = 150,
        },
        ...
  },
```
Reference: https://github.com/folke/lua-dev.nvim/blob/main/lua/lua-dev/sumneko.lua#L82-L93

Personally I don't like the `completion.callSnippet` and `workspace.maxPreload` behavior. The reasons are: (i) functions will show up as snippet entries in the completion engine (rather than kind of function); (ii) When analyzing some lua files greater than the `maxPreload` size, an input prompt will be asked. With the default value of `workspace.maxPreload` `nil`, it won't.

I think these values are very opinionated values and should not a part of this plugin (people can have them rather in their own lsp config files). At least these could be customizable through options for `lua_dev.setup { ...}`.

**Comment by wookayin** [comment]
FYI the current workaround I ended up using is:

```lua
lsp_setup_opts['sumneko_lua'] = vim.tbl_extend('force',
  require("lua-dev").setup {}, {
    settings = {
      Lua = {
        completion = { callSnippet = "Disable" },
        workspace = { maxPreload = nil },
      },
    },
  }
)
-- For example; do lspconfig with additional parameters, e.g., on_attach, capabilities, etc.
-- lspconfig.sumneko_lua.setup(lsp_setup_opts['sumneko_lua'])
```

**Comment by erwin** [comment]
@wookayin thanks so much for posting this!

In case anyone else is trying to get this working with a [NvChad based config](https://nvchad.github.io), you'll just want to create:

`~/.config/nvim/lua/custom/plugins/lspconfig.lua`

```lua
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }

      if server.name == "sumneko_lua" then
        require("lua-dev").setup {}, {
          settings = {
            Lua = {
              completion = { callSnippet = "Disable" },
              workspace = { maxPreload = nil },
            },
          },
        }
      end
end

return M
```

**Comment by wookayin** [comment]
@erwin I don't think your settings is correct. `require("lua-dev").setup{}` and `{...}` are supposed to be merged, but they aren't. `opts` should be used later like `server:setup(opts)`, but it isn't. I guess you wrongly trimmed out the config -- this code won't have any effect.

**Comment by erwin** [comment]
Thanks @wookayin ... I was so tired when I was working on the config that I didn't carefully note the difference between "getting rid of global symbol vim not defined" error message, and completely disabling my whole lsp configuration...

Thanks for pointing out that what I first posted couldn't have worked... 

I've tested it a little and it seems to be fine now.

**Comment by petobens** [comment]
@wookayin @erwin any pointers on how to use this with lsp-installer? If I uncomment the `if` bit in the following snippet then the lsp stops working alltogether:
```lua
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- FIXME: adding the following lines break everything
    -- if server.name == 'sumneko_lua' then
    -- opts.settings = require('lua-dev').setup().settings
    -- end

    server:setup(opts)
end)
```

**Comment by sabitm** [comment]
@petobens This setup works for me

```lua
if server.name == "sumneko_lua" then
  local luadev = require("lua-dev").setup {
    lspconfig = vim.tbl_deep_extend("force", server:get_default_options(), opts),
  }

  server:setup(luadev)
else
  server:setup(opts)
end

```

**Comment by petobens** [comment]
Thanks @sabitm . @folke what's the official/recommended way of doing it? Both (commented and uncommented) in the following snippet seem to work:
```lua
    if server.name == 'sumneko_lua' then
        -- opts.settings = require('lua-dev').setup().settings
        opts = vim.tbl_deep_extend('force', require('lua-dev').setup(), opts)
    end
```

**Comment by vedattt** [comment]
There is no longer a need to work around `callSnippet`:
- #47

**Comment by folke** [comment]
Please check for the new preferred setup in the docs. This should resolve all of this.
