### ISSUE TITLE
Is it necessary to have all .lua files in lua subdirectory?

### ISSUE THREAD

**Issue by vatosarmat** [folke/lua-dev.nvim#37]
Hello and thanks you for the plugin. It makes `neovim` configuration experience much better but I have one small question.  

All the user configurations and plugins I saw had their `.lua` files in subdirectory called `lua`, like `.config/nvim/lua/mappings.lua`. But I always preferred to have fewer directory levels so I put my files into just `.config/nvim` and it worked as long as I set `package.path` to `config/nvim/?.lua`. But it seems like your plugin doesn't support this: `sumneko` "go to definition" doesn't work until I put file with definition in `lua` subdirectory. Do I really have to do that to have "go to definition" working? Or is it possible to configure something?

Also I've found this commented out line and tried to uncomment it, but it didn't help
https://github.com/folke/lua-dev.nvim/blob/4331626b02f636433b504b9ab6a8c11fb9de4a24/lua/lua-dev/sumneko.lua#L44

**Comment by folke** [comment]
I just fixed another issue, that probably also now allows lua files not under a lua directory. Let me know if it wouldn't fix your issye
