### ISSUE TITLE
Library path suffixed with /lua

### ISSUE THREAD

**Issue by vanhtuan0409** [folke/lua-dev.nvim#38]
Hi @folke 
May I know if this is an error when suffixed library path with `/lua`? As I notice that we have already looking for files using `lua/?.lua`
https://github.com/folke/lua-dev.nvim/blob/main/lua/lua-dev/sumneko.lua#L14
Currently, I got no suggestions from installed plugins. Tried to remove this `/lua` suffix then everything works as expected.

![image](https://user-images.githubusercontent.com/8175932/147739099-0eb04a28-69d7-44df-9bdb-b7db3daf51ae.png)

**Comment by folke** [comment]
Something must have changed in Sumenko. I've just pushed some changes to fix this. Let me know if you have any more issues
