### ISSUE TITLE
Add "globals" option

### ISSUE THREAD

**Issue by kristijanhusak** [folke/lua-dev.nvim#4]
Hi,

it would be neat if we could provide additional globals to the configuration. Currently I'm doing this:

```lua
luadev.settings.Lua.diagnostics.globals = {'vim', 'describe', 'it', 'before_each', 'after_each'}
nvim_lsp.sumneko_lua.setup(luadev)
```

Having top level globals that would merge into existing one would be great.
Or even making all of these a default globals value.

**Comment by folke** [comment]
I actually added config merging this morning ;)

Check the [docs](https://github.com/folke/lua-dev.nvim#%EF%B8%8F--configuration)

**Comment by kristijanhusak** [comment]
Ok, thanks!
