### ISSUE TITLE
[BUG] Double Workspace Loaded on Sumneko 2.6.0

### ISSUE THREAD

**Issue by tigorlazuardi** [folke/lua-dev.nvim#41]
Two workspaces are loaded in the newest Sumneko lua server when using lua-dev. I can confirm this does not occur when not using lua-dev in lspconfig.

The effect of loading two workspaces is super slow startup for the lsp, and super slow autocompletes and goto definitions.

The proof of two workspaces loaded can be seen in the screenshot by using `lsp_status` indicator in the status line (the bottom row).

![image](https://user-images.githubusercontent.com/49936087/149743771-c3f5d68d-61ae-4fd2-a4b2-3bc5b36056e8.png)

This is most likely caused by the new workspaces feature. Can be seen from this compare tag [commits](https://github.com/sumneko/lua-language-server/compare/2.5.6...2.6.0).

**Comment by captainko** [comment]
I'm experiencing this too.

**Comment by captainko** [comment]
@folke can you check this one out? Because of this, the loading time has increased dramatically.

**Comment by folke** [comment]
I don't really see anything I can do to fix this?

Seems like a bug in Sumneko? As far as I can see, there's only one lsp client.

**Comment by tigorlazuardi** [comment]
Thank you for the answer. Downgrading `sumneko_lua` to `v2.5.6` fixed the issue. It seems best to wait until `sumneko_lua` to be stable before going to `v2.6.x` or higher.

I consider this issue from my side to be closed, but left the decision to close it to you.

**Comment by ikerurda** [comment]
Hi!
Could this be related?

warn message in `~/.cache/nvim/lsp.log`:
```
[WARN][2022-01-21 14:39:09] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
```
I'm getting 100% CPU usage and no response from the server.

I've also tried it without applying 
```lua
require("lua-dev").setup { lspconfig = M.general }
```
and the warning keeps appearing (I assume it has to do with sumneko_lua) but the CPU usage won't raise...

**Comment by folke** [comment]
The reason for this is https://github.com/sumneko/lua-language-server/issues/1596
