### ISSUE TITLE
module 'lspconfig' not found

### ISSUE THREAD

**Issue by gkzhb** [folke/lua-dev.nvim#42]
Can we add an option not to use nvim-lspconfig in #39 ? 
Or at least we need to note that this plugin requires nvim-lspconfig in README.

I'm using this plugin with coc.nvim. And lspconfig is not installed.

**Comment by wookayin** [comment]
This plugin is for nvim LSP, not for coc. You've got a wrong address.

**Comment by gkzhb** [comment]
OK, thanks for ur reply
