### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by max397574** [folke/lua-dev.nvim#45]
At the moments quite some functions are missing:
vim.keymap. ...
the autocommand functions
the user_command functions
vim.loop. ...

could you add this @folke ?

**Comment by ObserverOfTime** [comment]
I managed to generate the `autocmd` and `user_command` functions from nightly but it's still missing `vim.keymap`, `vim.filetype`, and `vim.loop`. Adding those seems to be tricky.

**Comment by max397574** [comment]
how did u generate the command and autocmd functions @ObserverOfTime

**Comment by max397574** [comment]
@folke could u update the data? (or explain how to do it)

**Comment by max397574** [comment]
I managed to generate the api functions
the keymap functions (vim.keymap) are generated but under `vim.set` and `vim.del`
 I have to see if I can do something about this

**Comment by max397574** [comment]
I did a hack for the other things
you can check out my fork for it
