### ISSUE TITLE
types/api.lua does not have vim.api.nvim_create_autocmd

### ISSUE THREAD

**Issue by mihirgogate** [folke/lua-dev.nvim#46]
nvim_create_autocmd was added in neovim version 0.7.
I saw a previous commit (https://github.com/folke/lua-dev.nvim/commit/60637315d665652c59a6a4f99a82f2308d11dd8f) with the title 'feat: updated docs to 0.7' which is why I thought the lua-dev does support the entire 0.7 neovim api.
However I dont see it in the docs (I checked types/api.lua and types/api1.lua). Is there anyway this could be added ?

**Comment by folke** [comment]
I just updated the API docs. Thanks!
