### ISSUE TITLE
completion for plugin modules

### ISSUE THREAD

**Issue by Chaitanyabsprip** [folke/lua-dev.nvim#49]
I see that the readme specifies I get completion for plugins in opt and start directories, I'm not sure whether that includes auto-completions for, say, `require('telescope.builtins').|` so completion on the `|` character.

how can I get completions for plugin modules

**Comment by max397574** [comment]
add them to the plugins list

**Comment by folke** [comment]
Should work, but it seems like there's a lot of magic happening inside `telescope.builtin`, which Sumneko doesnt like, so you get little results back
