### ISSUE TITLE
Couldn't find lua-language-server

### ISSUE THREAD

**Issue by IZenithy** [folke/lua-dev.nvim#55]
I don't know why, but it couldn't find lua-language . server

Error massage:
![2022-07-03_20:06:37](https://user-images.githubusercontent.com/82327047/177051146-100ace39-44d9-4466-b8c7-704214ada52e.jpg)

**Comment by folke** [comment]
With the new setup way, you no longer need to pass lua-dev options to lspconfig setup.

The error you're getting is unrelated to lua-dev. It seems you dont have sumneko installed
