### ISSUE TITLE
Treesitter annotations incomplete

### ISSUE THREAD

**Issue by smackesey** [folke/lua-dev.nvim#59]
The README says:

> full signature, docs and completion of vim.api, vim.treesitter, vim.lsp and others

However, it seems like `vim.treesitter` annotations are very spotty. I can't tell if they just haven't been done, or this is a bug. I'm inclined to think bug because the annotations look wrong, find below a screenshot of the popup for `vim.treesitter.parse_query`:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1531373/180614767-557360be-6363-495a-8728-2f01e2687157.png">

 The `nil.parse_query` part is clearly a bug, perhaps the same bug is interfering with getting the annotation info?

**Comment by folke** [comment]
There's no `parse_query`method on `vim.treesitter` as fas as I know.
I made a bunch of updates, so might be good to check if that resolves your issue.

Just to make sure, you are not using the `cmp-lua` source right? With `lua-dev` that's not needed and could conflict.
