### ISSUE TITLE
`nvim_replace_termcodes` missing return

### ISSUE THREAD

**Issue by kristijanhusak** [folke/lua-dev.nvim#60]
I noticed that [nvim_replace_termcodes](https://github.com/folke/lua-dev.nvim/blob/c6ac64c5d3228b517e5e8b075297d313c7436339/types/api.1.lua#L174) is missing a return statement. This causes some errors when I try to pass the escaped value to the function, it considers it nil instead of string

**Comment by folke** [comment]
The relevant docs `:help nvim_replace_termcodes` don't mention a return value, so **lua-dev** won't generate the emmy lua return annotation

**Comment by kristijanhusak** [comment]
Ah, ok, that makes sense. Thanks.
