### ISSUE TITLE
Usage in non-standard config directories

### ISSUE THREAD

**Issue by jose-elias-alvarez** [folke/lua-dev.nvim#64]
Hey! I switched over to the new config method introduced in ae74bc9987638da2e122aaaf155d6519f07e6197. Everything is working great, but I'm having an issue related to config directory resolution.

I keep my Neovim config in a separate `dotfiles` directory that's symlinked to `~/.config/nvim`. When I edit config files from the `dotfiles` directory, lua-dev doesn't inject its configuration (which makes sense, since the directory doesn't match the patterns it's looking for). Everything works as expected if I edit files directly from `~/.config/nvim`.

I imagine I'm not the only one in this situation, so I wonder if it makes sense to allow users to define additional config directories (or just define additional arbitrary directories that lua-dev should activate on). If that approach makes sense, I'm happy to put in a PR.

**Comment by folke** [comment]
Hi! You can use the `override` settings for this. You can find more info about it in the docs.

**Comment by jose-elias-alvarez** [comment]
My bad, I hadn't checked the latest commits before opening the issue. This is exactly what I needed, thank you!

**Comment by marcomayer** [comment]
I have exactly the same problem and stumbled over this but just can't get it to work. Things do work fine if I edit a file in the nvim plugin folder but my config...nope. Here's the setup, I did include the notify to see if it gets triggered and it does. Any ideas, @jose-elias-alvarez what does your setup look like?

```
require("neodev").setup({
	library = {
		enabled = true, 
		runtime = true,
		types = true,
		plugins = true,
	},
	setup_jsonls = true,
	override = function(root_dir, library)
		if require("neodev.util").has_file(root_dir, "~/.dotfiles/nvim/.config/nvim") then
			library.enabled = true
			library.plugins = true
			library.types = true
			library.plugins = true

			vim.notify("meh!")
		end
	end,
	lspconfig = true,
})
```

**Comment by folke** [comment]
what is your root_dir?

**Comment by marcomayer** [comment]
> what is your root_dir?
It's "/Users/marco/.dotfiles/nvim/.config/nvim"

**Comment by folke** [comment]
@marcomayer you say it works in `nvim`, so you mean it works in that `root_dir`?
But it doesnt work in other directories inside `"/Users/marco/.dotfiles"`?

That's how it supposed to be.

If you rather have Neodev work in all root_dirs, do soemthing like:

```lua
require("neodev").setup({
  override = function(root_dir, library)
       library.enabled = true
      library.plugins = true
  end,
})
```

**Comment by marcomayer** [comment]
Sorry @folke I wasn't clear on that. If I open a plugin within `~/.local/share/nvim/site/pack/packer/opt/` it works just fine. But when I want to edit my nvim config in `~/.dotfiles/nvim/.config/nvim` which is symlinked to `~/.config/nvim` then it doesn't. I thought I can get it to work with the override but maybe I misunderstood what it's for and how it works 🤔

**Comment by folke** [comment]
The override should work, just use the one I posted above.

**Comment by marcomayer** [comment]
> The override should work, just use the one I posted above.

Also doesn't work :/ Probably there's something off on my side, maybe the problem is that there are two workspace folders detected (also sumneko lua seems to start twice)

**Comment by jose-elias-alvarez** [comment]
This is what I'm doing, not sure if it works for your case:

```lua
require("neodev").setup({
    override = function(root_dir, library)
        if root_dir:match("dotfiles") then
            library.enabled = true
            library.plugins = true
        end
    end,
})
```
