### ISSUE TITLE
[Bug] completion for `require` will not work correctly because of duplication of `lua/`.

### ISSUE THREAD

**Issue by uga-rosa** [folke/lua-dev.nvim#65]
It seems to be a duplicate because this plugin is adding `/lua` to `workspace.library` and also adding `lua/` to `runtime.path`.
If I remove `lua/` from `runtime.path`, require completion will work correctly.

Before:
![image](https://user-images.githubusercontent.com/82267684/189504920-5cea8173-b5b8-449e-9642-930026fddcfb.png)

Trimed:
![image](https://user-images.githubusercontent.com/82267684/189504856-af1aeec9-276d-480a-9526-40791edc0fdc.png)

**Comment by folke** [comment]
Should be fixed now
