### ISSUE TITLE
[question]: the plugin `folke/settings.nvim` is not public available

### ISSUE THREAD

**Issue by younger-1** [folke/lua-dev.nvim#68]
I notice that the project has the file `.nvim.settings.json` and the commit d95e691 mentions `settings.nvim`. 
Just want to make sure if the plugin is still in development and not public available in case you forget to set it to public

**Comment by folke** [comment]
Good catch 😄 

I'm planning to release `settings.nvim` this week. Finalizing documentation right now

**Comment by younger-1** [comment]
Oh, excited to know this. Your plugins are awesome!
