### ISSUE TITLE
Don't show "diagnosing..." status

### ISSUE THREAD

**Issue by p00f** [folke/lua-dev.nvim#7]
Hello, thanks for this plugin, very helpful. There's a minor inconvenience - without this plugin, I only get loading status

![image](https://user-images.githubusercontent.com/36493671/119237141-0a0c6500-bb59-11eb-8af9-fac471cbf7e7.png)

with this plugin, I get "Diagnosing \<file\>" status too:

![image](https://user-images.githubusercontent.com/36493671/119237121-ea753c80-bb58-11eb-86a2-2187e29204d6.png)

This spams my statusline every time I make an edit, how do I disable this? (Setting `settings.Lua.window.progressBar` in lspconfig to false disables loading status too, although I've done this for now)

I use https://github.com/tjdevries/express_line.nvim with https://github.com/nvim-lua/lsp-status.nvim

**Comment by p00f** [comment]
My lsp setup is
```lua
local function on_init(client)
    client.config.flags = {}
    if ("flags")[client.config] then
        client.config.flags["allow_incremental_sync"] = true
        return nil
    end
end
local capabilities = vim.lsp.protocol.make_client_capabilities()
local on_attach = require("lsp-status").on_attach
local diag_handler = {
    ["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        severity_sort = true,
        underline = true,
        update_in_insert = false,
        virtual_text = { prefix = " \240\159\158\182" },
    }),
}
local luadev = require("lua-dev").setup({
    lspconfig = {
        capabilities = capabilities,
        cmd = {
            vim.fn.expand("/home/p00f/bin/lua-language-server/bin/Linux/lua-language-server"),
            "-E",
            vim.fn.expand("/home/p00f/bin/lua-language-server/main.lua"),
        },
        handlers = diag_handler,
        on_attach = on_attach,
        on_init = on_init,
        settings = {
            Lua = {
                completion = { keywordSnippet = true },
                diagnostics = { globals = { "vim", "wezterm" } },
                telemetry = { enable = true },
                window = { progressBar = false },
                workspace = { preloadFileSize = 170 },
            },
        },
    },
})
lspconfig.sumneko_lua.setup(luadev)

```

**Comment by folke** [comment]
I don't do anything special here. Not sure what you are experiencing differently. You probably had the diagnosing messages before, but there might be more now, because of the added plugins to your workspace?

But again, I didn't change any settings

**Comment by p00f** [comment]
In the second screenshot it says diagnosing for the **_current file_** while there's nothing in the first one
> But again, I didn't change any settings

:neutral_face: fair
