### ISSUE TITLE
doesn't respect some modules

### ISSUE THREAD

**Issue by max397574** [folke/lua-dev.nvim#70]
there are some problems like this https://github.com/folke/lua-dev.nvim/blob/e18c4ce4048497384972052d8118eeaa0a681ada/types/lua.lua#L563
which should be `vim.ui.select`
this can be fixed with something like this:
https://github.com/max397574/lua-dev.nvim/blob/81d6185ab28e18fc56ff092e842beec26c4650d9/lua/lua-dev/parser.lua#L140-L156
https://github.com/max397574/lua-dev.nvim/blob/81d6185ab28e18fc56ff092e842beec26c4650d9/lua/lua-dev/parser.lua#L164-L167
the vim.fs things would have to be added as well

**Comment by folke** [comment]
Hi!

You were totally right. The fix was to actually **not** generate any types for existing lua files.
Existing lua files are properly hooked in `types/vim.lua`

Fixed in https://github.com/folke/lua-dev.nvim/commit/130b35e0f671c5729d106a4fe113129cb979e4b1
