### ISSUE TITLE
`undefined global vim` in plugin directory

### ISSUE THREAD

**Issue by Kibadda** [folke/lua-dev.nvim#71]
When I'm working on my own plugins I'm getting `undefined global vim`.

I found this line in util.lua: 
https://github.com/folke/lua-dev.nvim/blob/3a9d849adb10369e2dbf07bd3690b073a74e732a/lua/lua-dev/util.lua#L26
This somehow returns `false` even though the lsp root directory contains a `lua` folder.
![grafik](https://user-images.githubusercontent.com/71396679/193023630-bfe1a23f-e006-477f-bb1e-1c72756bfa5c.png)

If I change the regex to `"/lua[/$]?"` it works again.

I don't know if this is a bug or not.

I'm using the default settings for `lua-dev`.

In the runtime path and for my nvim config it works fine.

**Comment by folke** [comment]
It's becuase you have the `stylua.toml` file in the `lua` directory. This will cause `lspconfig` to set the root dir to `my_plugin/lua` instead of `my_plugin`.

Move that file to `my_plugin` to fix it.

**Comment by Kibadda** [comment]
Thank you very much. :)
