### ISSUE TITLE
[Feature Request] EmmyLua Annotation Files For LuaJIT Stdlib

### ISSUE THREAD

**Issue by Rayqan** [folke/lua-dev.nvim#8]
First off thanks for making this plugin, even though I prefer to roll my own config your generated EmmyLua annotations are very, very, very useful. Looking around I couldn't seem to find an similar set of annotations for the LuaJIT's stdlib and was wondering if it is possible to also generate those as well.

**Comment by folke** [comment]
This plugin's sole focus is providing completions for the Neovim Lua API.

Stdlib is out of scope, since it's not part of Neovim Lua.

**Comment by Rayqan** [comment]
I understand, would you happen to know of any way to get sumenko's lsp to at least recognize nvim's lua stdlib functions such as print() without manually defining them (feel free to close).

**Comment by folke** [comment]
Oh, you mean all the standard functions availabel in LuaJIT? That should work out of the box. No configuration needed!

Did you properly set the runtime in the sumneko config to LuaJIT?

**Comment by Rayqan** [comment]
Hmm, I did set 'Lua.runtime.version' to 'LuaJIT' if that is what you are referencing. Sounds like this may be an issue with the lsp then?

**Comment by Rayqan** [comment]
Sorry didn't see the edit, yep that's exactly what I did.

**Comment by Rayqan** [comment]
Seems like it was indeed a configuration issue, thanks for the help.
