### ISSUE TITLE
Feature request: turn it approachable for other LSP clients?

### ISSUE THREAD

**Issue by oblitum** [folke/lua-dev.nvim#9]
Hi, thanks for this project. What about making its interface/docs more approachable to non nvim-lsp clients? After analyzing the source code I realized how to hack a fairly simple [coc-lua](https://github.com/josa42/coc-lua) configuration:

```lua
local lua_settings = require('lua-dev').setup().settings.Lua
lua_settings.workspace.library = require('lua-dev.sumneko').library()
lua_settings.workspace.library['/usr/share/nvim/runtime'] = nil
vim.fn['coc#config']('Lua', lua_settings)
```

**Comment by oblitum** [comment]
I think a reasonable start would go towards `Lua.workspace.library` to have `require('lua-dev.sumneko').library()` as default, instead of an empty table. Then it could be simply adopted as:

```lua
vim.fn['coc#config']('Lua', require('lua-dev').setup().settings.Lua)
```

Currently `require('lua-dev.sumneko').library()` is being automatically plugged into `Lua.workspace.library` only when `on_new_config` callback is necessarily called by nvim-lsp, to remove the workspace root for avoiding duplicates. But I think that having a full library than an empty one at first is better default.

**Comment by folke** [comment]
I just changed this so that setup also returns the full settings including the library.
As an aside, make sure to install the latest sumenko version 1.21.3. I pushed a fix there to dramatically increase performance so disabling the nvim runtime is no longer needed.
